---
version: "3.8"

services:
  kafka1:
    image: ssamantr/reactive-kafka:latest
    container_name: reactive-kafka-1
    hostname: kafka1
    ports:
      - "8081:8081"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s1.properties:/kafka/config/kraft/server.properties
      - ./data/b1:/tmp/kafka-logs

  kafka2:
    image: ssamantr/reactive-kafka:latest
    container_name: reactive-kafka-2
    hostname: kafka2
    ports:
      - "8082:8082"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s2.properties:/kafka/config/kraft/server.properties
      - ./data/b2:/tmp/kafka-logs

  kafka3:
    image: ssamantr/reactive-kafka:latest
    container_name: reactive-kafka-3
    hostname: kafka3
    ports:
      - "8083:8083"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s3.properties:/kafka/config/kraft/server.properties
      - ./data/b3:/tmp/kafka-logs