---
version: "3.8"
services:
  kafka1:
    image: ssamantr/reactive-kafka:latest
    container_name: reactive-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/server.properties:/kafka/config/kraft/server.properties
      - ./data:/tmp/kafka-logs